name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm" # Speeds up subsequent runs

      - name: Install Dependencies
        run: npm install

      - name: Run Unit Tests (Jest)
        # --forceExit ensures the job doesn't hang due to open database/server handles
        run: npm test -- --forceExit

      - name: Run E2E Tests (Playwright)
        run: |
          npx playwright install --with-deps
          npm start & 
          npx wait-on http://localhost:5050 --timeout 60000 
          npm run test:frontend
