name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20" # Matches your environment

      - name: Install Dependencies
        run: npm install

      - name: Run Unit Tests (Jest)
        run: npm test # Verifies your 6 passing tests

      - name: Run E2E Tests (Playwright)
        run: |
          npx playwright install --with-deps
          npm start & # Starts server in background
          sleep 10 # Waits for server to be ready
          npm run test:frontend # Runs your 9 UI tests
